// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace remojoConnectionTypes.Rdp {
	using Monobjc;
	using Monobjc.AppKit;
	
	
	public partial class PropertyPageRdpAdvancedRedirectionController {
		
		[IBOutlet()]
		[ObjectiveCIVar("checkBoxDiskDrives")]
		public virtual NSButton checkBoxDiskDrives {
			get {
				return this.GetInstanceVariable <NSButton>("checkBoxDiskDrives");
			}
			set {
				this.SetInstanceVariable <NSButton>("checkBoxDiskDrives", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("checkBoxPrinters")]
		public virtual NSButton checkBoxPrinters {
			get {
				return this.GetInstanceVariable <NSButton>("checkBoxPrinters");
			}
			set {
				this.SetInstanceVariable <NSButton>("checkBoxPrinters", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("imageViewAudio")]
		public virtual NSImageView imageViewAudio {
			get {
				return this.GetInstanceVariable <NSImageView>("imageViewAudio");
			}
			set {
				this.SetInstanceVariable <NSImageView>("imageViewAudio", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("imageViewDevices")]
		public virtual NSImageView imageViewDevices {
			get {
				return this.GetInstanceVariable <NSImageView>("imageViewDevices");
			}
			set {
				this.SetInstanceVariable <NSImageView>("imageViewDevices", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("popupButtonAudio")]
		public virtual NSPopUpButton popupButtonAudio {
			get {
				return this.GetInstanceVariable <NSPopUpButton>("popupButtonAudio");
			}
			set {
				this.SetInstanceVariable <NSPopUpButton>("popupButtonAudio", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("textFieldAudioLabel")]
		public virtual NSTextField textFieldAudioLabel {
			get {
				return this.GetInstanceVariable <NSTextField>("textFieldAudioLabel");
			}
			set {
				this.SetInstanceVariable <NSTextField>("textFieldAudioLabel", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("textFieldDevicesHeader")]
		public virtual NSTextField textFieldDevicesHeader {
			get {
				return this.GetInstanceVariable <NSTextField>("textFieldDevicesHeader");
			}
			set {
				this.SetInstanceVariable <NSTextField>("textFieldDevicesHeader", value);
			}
		}
	}
}
