// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace remojoConnectionTypes.Rdp {
	using Monobjc;
	using remojoApi;
	using Monobjc.AppKit;
	
	
	public partial class PropertyPageRdpMainController {
		
partial void ButtonComputerNameEditor_Action(Id sender);

		
		[IBOutlet()]
		[ObjectiveCIVar("buttonColor")]
		public virtual RmColorChooserButton buttonColor {
			get {
				return this.GetInstanceVariable <RmColorChooserButton>("buttonColor");
			}
			set {
				this.SetInstanceVariable <RmColorChooserButton>("buttonColor", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("buttonComputerNameEditor")]
		public virtual NSButton buttonComputerNameEditor {
			get {
				return this.GetInstanceVariable <NSButton>("buttonComputerNameEditor");
			}
			set {
				this.SetInstanceVariable <NSButton>("buttonComputerNameEditor", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("buttonIcon")]
		public virtual RmIconChooserButton buttonIcon {
			get {
				return this.GetInstanceVariable <RmIconChooserButton>("buttonIcon");
			}
			set {
				this.SetInstanceVariable <RmIconChooserButton>("buttonIcon", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("imageViewDescription")]
		public virtual NSImageView imageViewDescription {
			get {
				return this.GetInstanceVariable <NSImageView>("imageViewDescription");
			}
			set {
				this.SetInstanceVariable <NSImageView>("imageViewDescription", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("metadataView")]
		public virtual RoyalObjectMetadataView metadataView {
			get {
				return this.GetInstanceVariable <RoyalObjectMetadataView>("metadataView");
			}
			set {
				this.SetInstanceVariable <RoyalObjectMetadataView>("metadataView", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("textFieldComputerName")]
		public virtual NSTextField textFieldComputerName {
			get {
				return this.GetInstanceVariable <NSTextField>("textFieldComputerName");
			}
			set {
				this.SetInstanceVariable <NSTextField>("textFieldComputerName", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("textFieldComputerNameLabel")]
		public virtual NSTextField textFieldComputerNameLabel {
			get {
				return this.GetInstanceVariable <NSTextField>("textFieldComputerNameLabel");
			}
			set {
				this.SetInstanceVariable <NSTextField>("textFieldComputerNameLabel", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("textFieldConnectionDescription")]
		public virtual NSTextField textFieldConnectionDescription {
			get {
				return this.GetInstanceVariable <NSTextField>("textFieldConnectionDescription");
			}
			set {
				this.SetInstanceVariable <NSTextField>("textFieldConnectionDescription", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("textFieldConnectionDescriptionLabel")]
		public virtual NSTextField textFieldConnectionDescriptionLabel {
			get {
				return this.GetInstanceVariable <NSTextField>("textFieldConnectionDescriptionLabel");
			}
			set {
				this.SetInstanceVariable <NSTextField>("textFieldConnectionDescriptionLabel", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("textFieldCreatedBy")]
		public virtual NSTextField textFieldCreatedBy {
			get {
				return this.GetInstanceVariable <NSTextField>("textFieldCreatedBy");
			}
			set {
				this.SetInstanceVariable <NSTextField>("textFieldCreatedBy", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("textFieldCreatedByLabel")]
		public virtual NSTextField textFieldCreatedByLabel {
			get {
				return this.GetInstanceVariable <NSTextField>("textFieldCreatedByLabel");
			}
			set {
				this.SetInstanceVariable <NSTextField>("textFieldCreatedByLabel", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("textFieldDateCreated")]
		public virtual NSTextField textFieldDateCreated {
			get {
				return this.GetInstanceVariable <NSTextField>("textFieldDateCreated");
			}
			set {
				this.SetInstanceVariable <NSTextField>("textFieldDateCreated", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("textFieldDateCreatedLabel")]
		public virtual NSTextField textFieldDateCreatedLabel {
			get {
				return this.GetInstanceVariable <NSTextField>("textFieldDateCreatedLabel");
			}
			set {
				this.SetInstanceVariable <NSTextField>("textFieldDateCreatedLabel", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("textFieldDateModified")]
		public virtual NSTextField textFieldDateModified {
			get {
				return this.GetInstanceVariable <NSTextField>("textFieldDateModified");
			}
			set {
				this.SetInstanceVariable <NSTextField>("textFieldDateModified", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("textFieldDateModifiedLabel")]
		public virtual NSTextField textFieldDateModifiedLabel {
			get {
				return this.GetInstanceVariable <NSTextField>("textFieldDateModifiedLabel");
			}
			set {
				this.SetInstanceVariable <NSTextField>("textFieldDateModifiedLabel", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("textFieldDescription")]
		public virtual NSTextField textFieldDescription {
			get {
				return this.GetInstanceVariable <NSTextField>("textFieldDescription");
			}
			set {
				this.SetInstanceVariable <NSTextField>("textFieldDescription", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("textFieldDisplayName")]
		public virtual NSTextField textFieldDisplayName {
			get {
				return this.GetInstanceVariable <NSTextField>("textFieldDisplayName");
			}
			set {
				this.SetInstanceVariable <NSTextField>("textFieldDisplayName", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("textFieldDisplayNameLabel")]
		public virtual NSTextField textFieldDisplayNameLabel {
			get {
				return this.GetInstanceVariable <NSTextField>("textFieldDisplayNameLabel");
			}
			set {
				this.SetInstanceVariable <NSTextField>("textFieldDisplayNameLabel", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("textFieldModifiedBy")]
		public virtual NSTextField textFieldModifiedBy {
			get {
				return this.GetInstanceVariable <NSTextField>("textFieldModifiedBy");
			}
			set {
				this.SetInstanceVariable <NSTextField>("textFieldModifiedBy", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("textFieldModifiedByLabel")]
		public virtual NSTextField textFieldModifiedByLabel {
			get {
				return this.GetInstanceVariable <NSTextField>("textFieldModifiedByLabel");
			}
			set {
				this.SetInstanceVariable <NSTextField>("textFieldModifiedByLabel", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("textFieldPhysicalAddress")]
		public virtual NSTextField textFieldPhysicalAddress {
			get {
				return this.GetInstanceVariable <NSTextField>("textFieldPhysicalAddress");
			}
			set {
				this.SetInstanceVariable <NSTextField>("textFieldPhysicalAddress", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("textFieldPhysicalAddressLabel")]
		public virtual NSTextField textFieldPhysicalAddressLabel {
			get {
				return this.GetInstanceVariable <NSTextField>("textFieldPhysicalAddressLabel");
			}
			set {
				this.SetInstanceVariable <NSTextField>("textFieldPhysicalAddressLabel", value);
			}
		}
		
		[IBAction()]
		[ObjectiveCMessage("buttonComputerNameEditor_Action:")]
		public virtual void __ButtonComputerNameEditor_Action(Id sender) {
			this.ButtonComputerNameEditor_Action(sender);
		}
	}
}
