// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace remojoConnectionTypes.Rdp {
	using Monobjc;
	using Monobjc.AppKit;
	
	
	public partial class PropertyPageRdpAdvancedDisplayController {
		
partial void PopupButtonDesktopSize_Action(Id sender);

partial void PopupButtonResizeMode_Action(Id sender);

		
		[IBOutlet()]
		[ObjectiveCIVar("imageViewColors")]
		public virtual NSImageView imageViewColors {
			get {
				return this.GetInstanceVariable <NSImageView>("imageViewColors");
			}
			set {
				this.SetInstanceVariable <NSImageView>("imageViewColors", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("imageViewSize")]
		public virtual NSImageView imageViewSize {
			get {
				return this.GetInstanceVariable <NSImageView>("imageViewSize");
			}
			set {
				this.SetInstanceVariable <NSImageView>("imageViewSize", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("popupButtonColors")]
		public virtual NSPopUpButton popupButtonColors {
			get {
				return this.GetInstanceVariable <NSPopUpButton>("popupButtonColors");
			}
			set {
				this.SetInstanceVariable <NSPopUpButton>("popupButtonColors", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("popupButtonDesktopSize")]
		public virtual NSPopUpButton popupButtonDesktopSize {
			get {
				return this.GetInstanceVariable <NSPopUpButton>("popupButtonDesktopSize");
			}
			set {
				this.SetInstanceVariable <NSPopUpButton>("popupButtonDesktopSize", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("popupButtonResizeMode")]
		public virtual NSPopUpButton popupButtonResizeMode {
			get {
				return this.GetInstanceVariable <NSPopUpButton>("popupButtonResizeMode");
			}
			set {
				this.SetInstanceVariable <NSPopUpButton>("popupButtonResizeMode", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("textFieldColorsLabel")]
		public virtual NSTextField textFieldColorsLabel {
			get {
				return this.GetInstanceVariable <NSTextField>("textFieldColorsLabel");
			}
			set {
				this.SetInstanceVariable <NSTextField>("textFieldColorsLabel", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("textFieldCustomSizeHeight")]
		public virtual NSTextField textFieldCustomSizeHeight {
			get {
				return this.GetInstanceVariable <NSTextField>("textFieldCustomSizeHeight");
			}
			set {
				this.SetInstanceVariable <NSTextField>("textFieldCustomSizeHeight", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("textFieldCustomSizeHeightLabel")]
		public virtual NSTextField textFieldCustomSizeHeightLabel {
			get {
				return this.GetInstanceVariable <NSTextField>("textFieldCustomSizeHeightLabel");
			}
			set {
				this.SetInstanceVariable <NSTextField>("textFieldCustomSizeHeightLabel", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("textFieldCustomSizeWidth")]
		public virtual NSTextField textFieldCustomSizeWidth {
			get {
				return this.GetInstanceVariable <NSTextField>("textFieldCustomSizeWidth");
			}
			set {
				this.SetInstanceVariable <NSTextField>("textFieldCustomSizeWidth", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("textFieldCustomSizeWidthLabel")]
		public virtual NSTextField textFieldCustomSizeWidthLabel {
			get {
				return this.GetInstanceVariable <NSTextField>("textFieldCustomSizeWidthLabel");
			}
			set {
				this.SetInstanceVariable <NSTextField>("textFieldCustomSizeWidthLabel", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("textFieldDesktopSizeLabel")]
		public virtual NSTextField textFieldDesktopSizeLabel {
			get {
				return this.GetInstanceVariable <NSTextField>("textFieldDesktopSizeLabel");
			}
			set {
				this.SetInstanceVariable <NSTextField>("textFieldDesktopSizeLabel", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("textFieldResizeModeDescription")]
		public virtual NSTextField textFieldResizeModeDescription {
			get {
				return this.GetInstanceVariable <NSTextField>("textFieldResizeModeDescription");
			}
			set {
				this.SetInstanceVariable <NSTextField>("textFieldResizeModeDescription", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("textFieldResizeModeLabel")]
		public virtual NSTextField textFieldResizeModeLabel {
			get {
				return this.GetInstanceVariable <NSTextField>("textFieldResizeModeLabel");
			}
			set {
				this.SetInstanceVariable <NSTextField>("textFieldResizeModeLabel", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("textFieldSizeDescription")]
		public virtual NSTextField textFieldSizeDescription {
			get {
				return this.GetInstanceVariable <NSTextField>("textFieldSizeDescription");
			}
			set {
				this.SetInstanceVariable <NSTextField>("textFieldSizeDescription", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("viewCustomSize")]
		public virtual NSView viewCustomSize {
			get {
				return this.GetInstanceVariable <NSView>("viewCustomSize");
			}
			set {
				this.SetInstanceVariable <NSView>("viewCustomSize", value);
			}
		}
		
		[IBAction()]
		[ObjectiveCMessage("popupButtonDesktopSize_Action:")]
		public virtual void __PopupButtonDesktopSize_Action(Id sender) {
			this.PopupButtonDesktopSize_Action(sender);
		}
		
		[IBAction()]
		[ObjectiveCMessage("popupButtonResizeMode_Action:")]
		public virtual void __PopupButtonResizeMode_Action(Id sender) {
			this.PopupButtonResizeMode_Action(sender);
		}
	}
}
