// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace remojoConnectionTypes.Rdp {
	using Monobjc;
	using Monobjc.AppKit;
	
	
	public partial class PropertyPageRdpAdvancedMainController {
		
		partial void CheckBoxCustomPort_Action(Id sender);

		[IBOutlet()]
		[ObjectiveCIVar("checkBoxConsoleSession")]
		public virtual NSButton checkBoxConsoleSession {
			get {
				return this.GetInstanceVariable <NSButton>("checkBoxConsoleSession");
			}
			set {
				this.SetInstanceVariable <NSButton>("checkBoxConsoleSession", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("checkBoxCustomPort")]
		public virtual NSButton checkBoxCustomPort {
			get {
				return this.GetInstanceVariable <NSButton>("checkBoxCustomPort");
			}
			set {
				this.SetInstanceVariable <NSButton>("checkBoxCustomPort", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("imageViewHeader")]
		public virtual NSImageView imageViewHeader {
			get {
				return this.GetInstanceVariable <NSImageView>("imageViewHeader");
			}
			set {
				this.SetInstanceVariable <NSImageView>("imageViewHeader", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("textFieldCustomPort")]
		public virtual NSTextField textFieldCustomPort {
			get {
				return this.GetInstanceVariable <NSTextField>("textFieldCustomPort");
			}
			set {
				this.SetInstanceVariable <NSTextField>("textFieldCustomPort", value);
			}
		}
		
		[IBAction()]
		[ObjectiveCMessage("checkBoxCustomPort_Action:")]
		public virtual void __CheckBoxCustomPort_Action(Id sender) {
			this.CheckBoxCustomPort_Action(sender);
		}
	}
}
