// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace remojoConnectionTypes.Rdp {
	using Monobjc;
	using Monobjc.AppKit;
	
	
	public partial class PropertyPageRdpAdvancedPerformanceController {
		
		[IBOutlet()]
		[ObjectiveCIVar("checkBoxDesktopBackground")]
		public virtual NSButton checkBoxDesktopBackground {
			get {
				return this.GetInstanceVariable <NSButton>("checkBoxDesktopBackground");
			}
			set {
				this.SetInstanceVariable <NSButton>("checkBoxDesktopBackground", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("checkBoxFontSmoothing")]
		public virtual NSButton checkBoxFontSmoothing {
			get {
				return this.GetInstanceVariable <NSButton>("checkBoxFontSmoothing");
			}
			set {
				this.SetInstanceVariable <NSButton>("checkBoxFontSmoothing", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("checkBoxMenuAndWindowAnimations")]
		public virtual NSButton checkBoxMenuAndWindowAnimations {
			get {
				return this.GetInstanceVariable <NSButton>("checkBoxMenuAndWindowAnimations");
			}
			set {
				this.SetInstanceVariable <NSButton>("checkBoxMenuAndWindowAnimations", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("checkBoxShowWindowContentsWhileDragging")]
		public virtual NSButton checkBoxShowWindowContentsWhileDragging {
			get {
				return this.GetInstanceVariable <NSButton>("checkBoxShowWindowContentsWhileDragging");
			}
			set {
				this.SetInstanceVariable <NSButton>("checkBoxShowWindowContentsWhileDragging", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("checkBoxVisualStyles")]
		public virtual NSButton checkBoxVisualStyles {
			get {
				return this.GetInstanceVariable <NSButton>("checkBoxVisualStyles");
			}
			set {
				this.SetInstanceVariable <NSButton>("checkBoxVisualStyles", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("imageViewHeader")]
		public virtual NSImageView imageViewHeader {
			get {
				return this.GetInstanceVariable <NSImageView>("imageViewHeader");
			}
			set {
				this.SetInstanceVariable <NSImageView>("imageViewHeader", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("textFieldHeader")]
		public virtual NSTextField textFieldHeader {
			get {
				return this.GetInstanceVariable <NSTextField>("textFieldHeader");
			}
			set {
				this.SetInstanceVariable <NSTextField>("textFieldHeader", value);
			}
		}
	}
}
