// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace RoyalTSXConnectionTypes.Rdp {
	using Monobjc;
	using Monobjc.AppKit;
	
	
	public partial class PropertyPageRdpMainController {
		
		[IBOutlet()]
		[ObjectiveCIVar("imageViewDescription")]
		public virtual NSImageView imageViewDescription {
			get {
				return this.GetInstanceVariable <NSImageView>("imageViewDescription");
			}
			set {
				this.SetInstanceVariable <NSImageView>("imageViewDescription", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("textFieldComputerName")]
		public virtual NSTextField textFieldComputerName {
			get {
				return this.GetInstanceVariable <NSTextField>("textFieldComputerName");
			}
			set {
				this.SetInstanceVariable <NSTextField>("textFieldComputerName", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("textFieldConnectionDescription")]
		public virtual NSTextField textFieldConnectionDescription {
			get {
				return this.GetInstanceVariable <NSTextField>("textFieldConnectionDescription");
			}
			set {
				this.SetInstanceVariable <NSTextField>("textFieldConnectionDescription", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("textFieldCreatedBy")]
		public virtual NSTextField textFieldCreatedBy {
			get {
				return this.GetInstanceVariable <NSTextField>("textFieldCreatedBy");
			}
			set {
				this.SetInstanceVariable <NSTextField>("textFieldCreatedBy", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("textFieldDateCreated")]
		public virtual NSTextField textFieldDateCreated {
			get {
				return this.GetInstanceVariable <NSTextField>("textFieldDateCreated");
			}
			set {
				this.SetInstanceVariable <NSTextField>("textFieldDateCreated", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("textFieldDateModified")]
		public virtual NSTextField textFieldDateModified {
			get {
				return this.GetInstanceVariable <NSTextField>("textFieldDateModified");
			}
			set {
				this.SetInstanceVariable <NSTextField>("textFieldDateModified", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("textFieldDescription")]
		public virtual NSTextField textFieldDescription {
			get {
				return this.GetInstanceVariable <NSTextField>("textFieldDescription");
			}
			set {
				this.SetInstanceVariable <NSTextField>("textFieldDescription", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("textFieldDisplayName")]
		public virtual NSTextField textFieldDisplayName {
			get {
				return this.GetInstanceVariable <NSTextField>("textFieldDisplayName");
			}
			set {
				this.SetInstanceVariable <NSTextField>("textFieldDisplayName", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("textFieldModifiedBy")]
		public virtual NSTextField textFieldModifiedBy {
			get {
				return this.GetInstanceVariable <NSTextField>("textFieldModifiedBy");
			}
			set {
				this.SetInstanceVariable <NSTextField>("textFieldModifiedBy", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("textFieldPhysicalAddress")]
		public virtual NSTextField textFieldPhysicalAddress {
			get {
				return this.GetInstanceVariable <NSTextField>("textFieldPhysicalAddress");
			}
			set {
				this.SetInstanceVariable <NSTextField>("textFieldPhysicalAddress", value);
			}
		}
	}
}
